//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganesh_tiles.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GT_MVCEntities1 : DbContext
    {
        public GT_MVCEntities1()
            : base("name=GT_MVCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }

        public System.Data.Entity.DbSet<Ganesh_tiles.Model.tbl_Admin> tbl_Admin { get; set; }
    }
}
